# CMake generated Testfile for 
# Source directory: D:/git3/MagicLeap/LLM/dd/llama.cpp/tests
# Build directory: D:/git3/MagicLeap/LLM/dd/llama.cpp/build/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;73;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;73;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;73;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;73;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-llama-spm NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-llama-bpe "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;74;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-llama-bpe "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;74;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-llama-bpe "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;74;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-llama-bpe "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;74;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-llama-bpe NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-phi-3 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-phi-3 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-phi-3 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-phi-3 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-phi-3 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-falcon "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-falcon "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-falcon "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-falcon "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-falcon NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-bert-bge "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-bert-bge "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-bert-bge "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-bert-bge "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-bert-bge NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-starcoder "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-starcoder "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-starcoder "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-starcoder "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-starcoder NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-gpt-2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-gpt-2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-gpt-2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-gpt-2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-gpt-2 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-refact "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-refact "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-refact "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-refact "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-refact NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-command-r "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-command-r "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-command-r "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-command-r "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-command-r NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-qwen2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-qwen2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-qwen2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-qwen2 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-qwen2 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-1-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-tokenizer-1-spm.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;111;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-1-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-tokenizer-1-spm.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;111;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-1-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-tokenizer-1-spm.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;111;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-1-llama-spm "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-tokenizer-1-spm.exe" "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;22;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;111;llama_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-1-llama-spm NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-quantize-fns "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;115;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-quantize-fns "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;115;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-quantize-fns "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;115;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-quantize-fns "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;115;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-quantize-fns NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-quantize-perf "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;116;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-quantize-perf "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;116;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-quantize-perf "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;116;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-quantize-perf "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;116;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-quantize-perf NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-sampling "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-sampling.exe")
  set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;117;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-sampling "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-sampling.exe")
  set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;117;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-sampling "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-sampling.exe")
  set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;117;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-sampling "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-sampling.exe")
  set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;117;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-sampling NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-chat-template "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;118;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-chat-template "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;118;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-chat-template "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;118;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-chat-template "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;118;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-chat-template NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-grammar-parser "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-grammar-parser.exe")
  set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;120;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-grammar-parser "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-grammar-parser.exe")
  set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;120;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-grammar-parser "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-grammar-parser.exe")
  set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;120;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-grammar-parser "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-grammar-parser.exe")
  set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;120;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-grammar-parser NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-llama-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-llama-grammar.exe")
  set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;121;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-llama-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-llama-grammar.exe")
  set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;121;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-llama-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-llama-grammar.exe")
  set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;121;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-llama-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-llama-grammar.exe")
  set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;121;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-llama-grammar NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-grammar-integration "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-grammar-integration.exe")
  set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;122;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-grammar-integration "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-grammar-integration.exe")
  set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;122;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-grammar-integration "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-grammar-integration.exe")
  set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;122;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-grammar-integration "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-grammar-integration.exe")
  set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;122;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-grammar-integration NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-grad0 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-grad0.exe")
  set_tests_properties(test-grad0 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;123;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-grad0 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-grad0.exe")
  set_tests_properties(test-grad0 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;123;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-grad0 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-grad0.exe")
  set_tests_properties(test-grad0 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;123;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-grad0 "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-grad0.exe")
  set_tests_properties(test-grad0 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;123;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-grad0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-backend-ops "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;125;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-backend-ops "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;125;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-backend-ops "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;125;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-backend-ops "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;125;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-backend-ops NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-rope "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;127;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-rope "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;127;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-rope "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;127;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-rope "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;127;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-rope NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-model-load-cancel "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;129;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-model-load-cancel "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;129;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-model-load-cancel "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;129;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-model-load-cancel "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;129;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-model-load-cancel NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-autorelease "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;130;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-autorelease "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;130;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-autorelease "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;130;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-autorelease "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;130;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-autorelease NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-json-schema-to-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Debug/test-json-schema-to-grammar.exe")
  set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/.." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-json-schema-to-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/Release/test-json-schema-to-grammar.exe")
  set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/.." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-json-schema-to-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/MinSizeRel/test-json-schema-to-grammar.exe")
  set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/.." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-json-schema-to-grammar "D:/git3/MagicLeap/LLM/dd/llama.cpp/build/bin/RelWithDebInfo/test-json-schema-to-grammar.exe")
  set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/.." _BACKTRACE_TRIPLES "D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;59;add_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/git3/MagicLeap/LLM/dd/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-json-schema-to-grammar NOT_AVAILABLE)
endif()
